/* AURORA workstation — per-deployment configuration (generated by rollout).
 *
 * Landing disease program for this deployment. All nine programs remain
 * switchable at runtime; this only chooses the program the workstation
 * opens to, so this module repo lands on the program it belongs to.
 *
 * Valid program ids: glioma · hydro · spina · tethered · dwm ·
 *                    enceph · arach · cranio · chiari
 */
window.AURORA_DEFAULT_DZ = 'cranio';
window.AURORA_DEPLOY = { repo: 'aurora-cranio', program: 'cranio' };
